# admin roads

ged_admin_dashboard:
    path:    /
    defaults: { _controller: GedBundle:Admin:showDashboard }

ged_addcategory:
    path:    /newcategory
    defaults: { _controller: GedBundle:Admin:addCategory }

ged_removecategory:
    path:    /removecategory
    defaults: { _controller: GedBundle:Admin:removeCategory }

ged_removeUser:
    path:    /removeuser
    defaults: { _controller: GedBundle:Admin:removeUser }