<?php

namespace CS\GrcBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
	public function newcomments()
	{
    	$qb = $this->createQueryBuilder('u');
    	$qb->select('u')
    		->where('u.author = ?3')
			->orderBy('u.date', 'DESC')
			->setFirstResult(0)
   			->setMaxResults(5)
   			->setParameter(3, "Client");

    return $qb->getQuery()->getResult();
	}
}
