<?php

namespace CS\GrcBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GrccategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrccategoryRepository extends EntityRepository
{
}
