<?php

namespace CS\GrcBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GrcpriorityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrcpriorityRepository extends EntityRepository
{
}
