<?php

namespace CS\GrcBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GrcstatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrcstatusRepository extends EntityRepository
{
}
