<?php

namespace CS\GrcBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends EntityRepository
{
	public function recherche($keyword)
	{
    	$qb = $this->createQueryBuilder('u');
    	$qb->select('u')
			->where('u.id LIKE :keyword OR u.idcategory LIKE :keyword OR u.idsouscategory LIKE :keyword OR u.content LIKE :keyword')
			->setParameter('keyword', '%'.$keyword.'%');

    return $qb->getQuery()->getResult();
	}

	public function newtickets()
	{
    	$qb = $this->createQueryBuilder('u');
    	$qb->select('u')
			->orderBy('u.date', 'DESC')
			->setFirstResult(0)
   			->setMaxResults(5);

    return $qb->getQuery()->getResult();
	}

	public function highlyurgent()
	{
    	$qb = $this->createQueryBuilder('u');
    	$qb->select('u')
    		->where('u.priority = ?1')
			->orderBy('u.date', 'DESC')
			->setFirstResult(0)
   			->setMaxResults(5)
   			->setParameter(1, "Très urgent");

    return $qb->getQuery()->getResult();
	}

	public function urgent()
	{
    	$qb = $this->createQueryBuilder('u');
    	$qb->select('u')
    		->where('u.priority = ?2')
			->orderBy('u.date', 'DESC')
			->setFirstResult(0)
   			->setMaxResults(5)
   			->setParameter(2, "Urgent");

    return $qb->getQuery()->getResult();
	}

}
