<?php

namespace CS\GrcBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends EntityRepository
{
	public function recherche($keyword)
	{
    	$qb = $this->createQueryBuilder('u');
    	$qb->select('u')
			->where('u.id LIKE :keyword OR u.idcategory LIKE :keyword OR u.idsouscategory LIKE :keyword OR u.content LIKE :keyword')
			->setParameter('keyword', '%'.$keyword.'%');

    return $qb->getQuery()->getResult();
	}
}
