<?php

namespace CS\GedBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GedtagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GedtagRepository extends EntityRepository
{
	public function tagSearch($word)
	{
		$queryBuilder = $this->createQueryBuilder('f');

		$queryBuilder
			->where('f.name LIKE :word')
			->setParameter('word', '%'.$word.'%');

		// On récupère la Query à partir du QueryBuilder
	    $query = $queryBuilder->getQuery();

	    // On récupère les résultats à partir de la Query
	    $results = $query->getResult();

		// On retourne ces résultats
	    return $results;
	}
}
