<?php

namespace CS\GedBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GeduserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeduserRepository extends EntityRepository
{
}
