<?php

namespace CS\GedBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LinkbookmarkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkbookmarkRepository extends EntityRepository
{
	public function findFav ($iduser)
	{	
		$qb = $this->createQueryBuilder('a');
		$qb
			array ("iduser"=>$iduser),
			array ($orderBy = 'desc'),
	  		$limit  = 5,
	  		$offset = null
  		);
	}
}
