ged_login:
    path:     /login
    defaults: { _controller: GedBundle:Security:login }

ged_register:
    path:     /admin/register
    defaults: { _controller: GedBundle:Registration:register }

ged_homepage:
    path:     /
    defaults: { _controller: GedBundle:Default:index }

